created workflows folder and added linters.yml file
r-ahmed2022/Portfolio-Riyaz pull request #1
Opened 2022-04-20 15:51 UTC by r-ahmed2022

2022-04-23 17:08 UTC, KDlamini requested changes
### Hi @r-ahmed2022 🙋‍♀️,  

Excellent work! 💯 
You have done a great job creating the mobile setup according to the Figma design. 🎊 🥳 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Correct PR title
✔️  Correct use of Gitflow 
✔️  Good and descriptive README
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️
 
-  Please write a proper Pull Request description about the steps you took to set up the toolbar and the headlines. The simplest way to do this is to list the project requirements that are on the project activity. The good news is that you can still edit the description, it's not too late 💪🏾

 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 17:08 UTC, KDlamini commented on index.html
> +                         <span class="job-title">I’am a Software Developer</span>
You have a typo here. Kindly use `I'm` or `I am` instead of `I'am` on your `<span>` text.

Otherwise, everything on your website is perfect. Fantastic job!!! 💯 
Good luck and happy coding 🥂

2022-04-23 18:22 UTC, r-ahmed2022 commented on css/style.css
> +  box-shadow: 3px 3px 3px 3px gray;
Thank you , sure would heed your advise and incorporate the changes

2022-04-23 18:25 UTC, r-ahmed2022 commented on index.html
> +                            </div>
I had done it before in my original design but felt unnecessary in this design. However, as you have mentioned that we have to replicate exactly as specified in the Figma design and also working in a team , sometimes it is important , so it makes sense , and would update them ..

2022-04-23 18:26 UTC, r-ahmed2022 commented on index.html
> +                         <span class="job-title">I’am a Software Developer</span>
Thank you, sure, would correct the type error

2022-04-23 18:36 UTC, r-ahmed2022 commented on index.html
> +                            </div>
Thank you for providing valauble info

2022-04-23 23:44 UTC, r-ahmed2022 commented on index.html
> +                         <span class="job-title">I’am a Software Developer</span>
done

2022-04-24 14:56 UTC, r-ahmed2022 commented
Update the pull request with descriptive title as advised

2022-04-27 16:32 UTC, ShadyShawkat requested changes
## Hi @r-ahmed2022, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +  </body>
- Please try to stick as much as possible to the Figma design, which includes:
   - [ ] Removing the extra space around the design to match the Figma design. (This is caused by the extra `padding` on the container and the default `margin` given by the browser to the `body`)
   - [ ] Adjusting the background image not to overlap with the text.
   - [ ] Adjusting the background image to be all the way to the right to match the Figma design.
   - [ ] Using the same font weight and size of the "I’m a Software Developer" text to match the Figma design.
   - [ ] Editing the icons so that they don't overlap with the background image and display properly without white borders.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/165564777-f0e5dd0a-7253-463e-89ef-aeb48711c735.png) | ![image](https://user-images.githubusercontent.com/62290545/165563216-b00fdd5b-90ec-4870-8367-a8fd344898c7.png) |

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +                        </div>
- [ ] It's considered good practice to put background images in the actual background of a container instead of using an `img` tag. Kindly change this image to be displayed as a background-img of its parent container.

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +                               </ul>
- [x] Please wrap the social media links with an `a` tag each. You can use something like the following:
```
<ul>
   <li>
      <a>
         <img> first icon
      </a>
   </li>
   <li>
      <a>
         <img> second icon
      </a>
   </li>
   ...
</ul>
```

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +                        </ul>
- [x] Please wrap the social media links with an `a` tag each. You can use something like the following:
```
<ul>
   <li>
      <a>
         <img> first icon
      </a>
   </li>
   <li>
      <a>
         <img> second icon
      </a>
   </li>
   ...
</ul>
```

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +                        <nav id="navbar">
- [ ] Please make the logo of your page to be wrapped in an `a` tag. This can later work as a link to the home page.

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +       </head>
- [ ] Please change the title of your page to be something more personal and professional like 'Riyaz's Portfolio' or anything similar.

2022-04-27 16:32 UTC, ShadyShawkat commented on index.html
> +                            don’t hestiate to contact me.</blockquote>
- [ ] Kindly change this to be a `p` tag instead, for semantic purposes.

2022-04-27 20:22 UTC, r-ahmed2022 commented on index.html
> +                        </div>
changed to background image as suggested

2022-04-27 20:32 UTC, r-ahmed2022 commented on index.html
> +                               </ul>
Updated the social icons with hyperlinks

2022-04-27 20:37 UTC, r-ahmed2022 commented on index.html
> +       </head>
updated title as advised

2022-04-27 20:38 UTC, r-ahmed2022 commented on index.html
> +                            don’t hestiate to contact me.</blockquote>
done

2022-04-27 21:19 UTC, JuliCarracedo approved these changes
# Status: Approved ✔️
Hi @r-ahmed2022 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 21:23 UTC, merged